dist: xenial
language: php

php:
  - "7.2"
  - "7.1"
  - "5.6"

# matrix:
#  allow_failures:


env:
  - DOKUWIKI=master
  - DOKUWIKI=stable

before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install:
  - sh travis.sh

script:
  - cd _test && PRESERVE_TMP=false phpunit --stderr --group plugin_snow --verbose --debug
