language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

matrix:
  fast_finish: true
  allow_failures:
  - php: "7.0"

env:
  - DOKUWIKI=master
  - DOKUWIKI=stable

before_install:
  - phpunit --version
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install:
  - sh travis.sh
  # Force PHPUnit 7 
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then wget -v -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi

before_script:
  - phpunit --version

script:
  - cd _test && PRESERVE_TMP=false phpunit --stderr --group plugin_snow --verbose --debug
