dist: xenial
language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

# matrix:
#  allow_failures:


env:
  - DOKUWIKI=master
  - DOKUWIKI=stable

before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install:
  - sh travis.sh
  # Force PHPUnit 7 
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi

before_script:
  - test -z "$DISABLE_FUNCTIONS" || echo "disable_functions=$DISABLE_FUNCTIONS" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpunit --version

script:
  - cd _test && PRESERVE_TMP=false phpunit --stderr --group plugin_snow --verbose --debug
